"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import acme_client
from acme_client.model.paginate_response_edges_node import PaginateResponseEdgesNode


class TestPaginateResponseEdgesNode(unittest.TestCase):
    """PaginateResponseEdgesNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginateResponseEdgesNode(self):
        """Test PaginateResponseEdgesNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginateResponseEdgesNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
