"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import acme_client
from acme_client.model.paginate_response_page_info import PaginateResponsePageInfo


class TestPaginateResponsePageInfo(unittest.TestCase):
    """PaginateResponsePageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginateResponsePageInfo(self):
        """Test PaginateResponsePageInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginateResponsePageInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
