"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import acme_client
from acme_client.model.user import User
globals()['User'] = User
from acme_client.model.create_with_array_request import CreateWithArrayRequest


class TestCreateWithArrayRequest(unittest.TestCase):
    """CreateWithArrayRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateWithArrayRequest(self):
        """Test CreateWithArrayRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateWithArrayRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
