"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import unittest

import acme_client
from acme_client.api.miscellaneous_api import MiscellaneousApi  # noqa: E501


class TestMiscellaneousApi(unittest.TestCase):
    """MiscellaneousApi unit test stubs"""

    def setUp(self):
        self.api = MiscellaneousApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_paginate(self):
        """Test case for paginate

        Pagination sandbox  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
