/*
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.acme.client.api;

import com.acme.client.ApiCallback;
import com.acme.client.ApiClient;
import com.acme.client.ApiException;
import com.acme.client.ApiResponse;
import com.acme.client.Configuration;
import com.acme.client.Pair;
import com.acme.client.ProgressRequestBody;
import com.acme.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.acme.client.model.PaginateRequest;
import com.acme.client.model.PaginateResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class MiscellaneousApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MiscellaneousApi() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public MiscellaneousApi(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call paginateCall(PaginateRequest paginateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = paginateRequest;

        // create path and map variables
        String localVarPath = "/pagination";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call paginateValidateBeforeCall(PaginateRequest paginateRequest, final ApiCallback _callback) throws ApiException {
        return paginateCall(paginateRequest, _callback);

    }


    private ApiResponse<PaginateResponse> paginateWithHttpInfo(PaginateRequest paginateRequest) throws ApiException {
        okhttp3.Call localVarCall = paginateValidateBeforeCall(paginateRequest, null);
        Type localVarReturnType = new TypeToken<PaginateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call paginateAsync(PaginateRequest paginateRequest, final ApiCallback<PaginateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = paginateValidateBeforeCall(paginateRequest, _callback);
        Type localVarReturnType = new TypeToken<PaginateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class PaginateRequestBuilder {
        private Integer first;
        private String after;

        private PaginateRequestBuilder() {
        }

        /**
         * Set first
         * @param first  (optional)
         * @return PaginateRequestBuilder
         */
        public PaginateRequestBuilder first(Integer first) {
            this.first = first;
            return this;
        }
        
        /**
         * Set after
         * @param after  (optional)
         * @return PaginateRequestBuilder
         */
        public PaginateRequestBuilder after(String after) {
            this.after = after;
            return this;
        }
        
        /**
         * Build call for paginate
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            PaginateRequest paginateRequest = buildBodyParams();
            return paginateCall(paginateRequest, _callback);
        }

        private PaginateRequest buildBodyParams() {
            PaginateRequest paginateRequest = new PaginateRequest();
            paginateRequest.first(this.first);
            paginateRequest.after(this.after);
            return paginateRequest;
        }

        /**
         * Execute paginate request
         * @return PaginateResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
         </table>
         */
        public PaginateResponse execute() throws ApiException {
            PaginateRequest paginateRequest = buildBodyParams();
            ApiResponse<PaginateResponse> localVarResp = paginateWithHttpInfo(paginateRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute paginate request with HTTP info returned
         * @return ApiResponse&lt;PaginateResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<PaginateResponse> executeWithHttpInfo() throws ApiException {
            PaginateRequest paginateRequest = buildBodyParams();
            return paginateWithHttpInfo(paginateRequest);
        }

        /**
         * Execute paginate request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<PaginateResponse> _callback) throws ApiException {
            PaginateRequest paginateRequest = buildBodyParams();
            return paginateAsync(paginateRequest, _callback);
        }
    }

    /**
     * Pagination sandbox
     * Iterate through a bunch of items
     * @return PaginateRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PaginateRequestBuilder paginate() throws IllegalArgumentException {
        return new PaginateRequestBuilder();
    }
}
