/*
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.acme.client.api;

import com.acme.client.ApiException;
import com.acme.client.model.PaginateRequest;
import com.acme.client.model.PaginateResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MiscellaneousApi
 */
@Disabled
public class MiscellaneousApiTest {

    private final MiscellaneousApi api = new MiscellaneousApi();

    /**
     * Pagination sandbox
     *
     * Iterate through a bunch of items
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void paginateTest() throws ApiException {
        PaginateRequest paginateRequest = null;
        PaginateResponse response = api.paginate(paginateRequest);
        // TODO: test validations
    }

}
