/*
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.acme.client.api;

import com.acme.client.ApiException;
import com.acme.client.ApiClient;
import com.acme.client.ApiException;
import com.acme.client.Configuration;
import com.acme.client.model.PaginateRequest;
import com.acme.client.model.PaginateResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MiscellaneousApi
 */
@Disabled
public class MiscellaneousApiTest {

    private static MiscellaneousApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new MiscellaneousApi(apiClient);
    }

    /**
     * Pagination sandbox
     *
     * Iterate through a bunch of items
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void paginateTest() throws ApiException {
        Integer first = null;
        String after = null;
        PaginateResponse response = api.paginate()
                .first(first)
                .after(after)
                .execute();
        // TODO: test validations
    }

}
