/*
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.acme.client.api;

import com.acme.client.ApiException;
import com.acme.client.ApiClient;
import com.acme.client.ApiException;
import com.acme.client.Configuration;
import com.acme.client.model.Category;
import java.io.File;
import com.acme.client.model.ModelApiResponse;
import com.acme.client.model.Pet;
import com.acme.client.model.Tag;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PetApi
 */
@Disabled
public class PetApiTest {

    private static PetApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PetApi(apiClient);
    }

    /**
     * Add a new pet to the store
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addTest() throws ApiException {
        String name = null;
        List<String> photoUrls = null;
        List<Tag> tags = null;
        Long id = null;
        Category category = null;
        String status = null;
        Pet response = api.add(name, photoUrls)
                .tags(tags)
                .id(id)
                .category(category)
                .status(status)
                .execute();
        // TODO: test validations
    }

    /**
     * Deletes a pet
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        Long petId = null;
        api.delete(petId)
                .execute();
        // TODO: test validations
    }

    /**
     * Finds Pets by status
     *
     * Multiple status values can be provided with comma separated strings
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findByStatusTest() throws ApiException {
        List<String> status = null;
        List<Pet> response = api.findByStatus(status)
                .execute();
        // TODO: test validations
    }

    /**
     * Finds Pets by tags
     *
     * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findByTagsTest() throws ApiException {
        List<String> tags = null;
        List<Pet> response = api.findByTags(tags)
                .execute();
        // TODO: test validations
    }

    /**
     * Find pet by ID
     *
     * Returns a single pet
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        Long petId = null;
        Pet response = api.getById(petId)
                .execute();
        // TODO: test validations
    }

    /**
     * Update an existing pet
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        String name = null;
        List<String> photoUrls = null;
        List<Tag> tags = null;
        Long id = null;
        Category category = null;
        String status = null;
        Pet response = api.update(name, photoUrls)
                .tags(tags)
                .id(id)
                .category(category)
                .status(status)
                .execute();
        // TODO: test validations
    }

    /**
     * Updates a pet in the store with form data
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateWithFormTest() throws ApiException {
        Long petId = null;
        String name = null;
        String status = null;
        api.updateWithForm(petId)
                .name(name)
                .status(status)
                .execute();
        // TODO: test validations
    }

    /**
     * uploads an image
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadImageTest() throws ApiException {
        Long petId = null;
        String additionalMetadata = null;
        File _file = null;
        ModelApiResponse response = api.uploadImage(petId)
                .additionalMetadata(additionalMetadata)
                ._file(_file)
                .execute();
        // TODO: test validations
    }

}
