/*
OpenAPI Petstore

Testing PetApiService

*/

// Code generated by Konfig (https://konfigthis.com);

package acme

import (
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "github.com/konfig-dev/acme-sdks/go"
)

func Test_acme_PetApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test PetApiService AddPet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.PetApi.AddPet().Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test PetApiService DeletePet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var petId int64

        resp, httpRes, err := apiClient.PetApi.DeletePet(petId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test PetApiService FindPetsByStatus", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.PetApi.FindPetsByStatus().Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test PetApiService FindPetsByTags", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.PetApi.FindPetsByTags().Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test PetApiService GetPetById", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var petId int64

        resp, httpRes, err := apiClient.PetApi.GetPetById(petId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test PetApiService UpdatePet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.PetApi.UpdatePet().Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test PetApiService UpdatePetWithForm", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var petId int64

        resp, httpRes, err := apiClient.PetApi.UpdatePetWithForm(petId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test PetApiService UploadFile", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var petId int64

        resp, httpRes, err := apiClient.PetApi.UploadFile(petId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
