/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Acme.Net.Client;
using Acme.Net.Api;
// uncomment below to import models
//using Acme.Net.Model;

namespace Acme.Net.Test.Api
{
    /// <summary>
    ///  Class for testing MiscellaneousApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MiscellaneousApiTests : IDisposable
    {
        private MiscellaneousApi instance;

        public MiscellaneousApiTests()
        {
            instance = new MiscellaneousApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MiscellaneousApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MiscellaneousApi
            //Assert.IsType<MiscellaneousApi>(instance);
        }

        /// <summary>
        /// Test Paginate
        /// </summary>
        [Fact]
        public void PaginateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PaginateRequest paginateRequest = null;
            //var response = instance.Paginate(paginateRequest);
            //Assert.IsType<PaginateResponse>(response);
        }
    }
}
