/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.Net.Api;
using Acme.Net.Model;
using Acme.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.Net.Test.Model
{
    /// <summary>
    ///  Class for testing Category
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CategoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Category
        //private Category instance;

        public CategoryTests()
        {
            // TODO uncomment below to create an instance of Category
            //instance = new Category();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Category
        /// </summary>
        [Fact]
        public void CategoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" Category
            //Assert.IsType<Category>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
