/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.Net.Api;
using Acme.Net.Model;
using Acme.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.Net.Test.Model
{
    /// <summary>
    ///  Class for testing PaginateResponsePageInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginateResponsePageInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginateResponsePageInfo
        //private PaginateResponsePageInfo instance;

        public PaginateResponsePageInfoTests()
        {
            // TODO uncomment below to create an instance of PaginateResponsePageInfo
            //instance = new PaginateResponsePageInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginateResponsePageInfo
        /// </summary>
        [Fact]
        public void PaginateResponsePageInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginateResponsePageInfo
            //Assert.IsType<PaginateResponsePageInfo>(instance);
        }


        /// <summary>
        /// Test the property 'HasNextPage'
        /// </summary>
        [Fact]
        public void HasNextPageTest()
        {
            // TODO unit test for the property 'HasNextPage'
        }
        /// <summary>
        /// Test the property 'HasPreviousPage'
        /// </summary>
        [Fact]
        public void HasPreviousPageTest()
        {
            // TODO unit test for the property 'HasPreviousPage'
        }
        /// <summary>
        /// Test the property 'StartCursor'
        /// </summary>
        [Fact]
        public void StartCursorTest()
        {
            // TODO unit test for the property 'StartCursor'
        }
        /// <summary>
        /// Test the property 'EndCursor'
        /// </summary>
        [Fact]
        public void EndCursorTest()
        {
            // TODO unit test for the property 'EndCursor'
        }

    }

}
