/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.Net.Api;
using Acme.Net.Model;
using Acme.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.Net.Test.Model
{
    /// <summary>
    ///  Class for testing PaginateResponseEdges
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginateResponseEdgesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginateResponseEdges
        //private PaginateResponseEdges instance;

        public PaginateResponseEdgesTests()
        {
            // TODO uncomment below to create an instance of PaginateResponseEdges
            //instance = new PaginateResponseEdges();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginateResponseEdges
        /// </summary>
        [Fact]
        public void PaginateResponseEdgesInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginateResponseEdges
            //Assert.IsType<PaginateResponseEdges>(instance);
        }


        /// <summary>
        /// Test the property 'Node'
        /// </summary>
        [Fact]
        public void NodeTest()
        {
            // TODO unit test for the property 'Node'
        }

    }

}
