/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.Net.Api;
using Acme.Net.Model;
using Acme.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.Net.Test.Model
{
    /// <summary>
    ///  Class for testing PaginateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginateRequest
        //private PaginateRequest instance;

        public PaginateRequestTests()
        {
            // TODO uncomment below to create an instance of PaginateRequest
            //instance = new PaginateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginateRequest
        /// </summary>
        [Fact]
        public void PaginateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginateRequest
            //Assert.IsType<PaginateRequest>(instance);
        }


        /// <summary>
        /// Test the property 'First'
        /// </summary>
        [Fact]
        public void FirstTest()
        {
            // TODO unit test for the property 'First'
        }
        /// <summary>
        /// Test the property 'After'
        /// </summary>
        [Fact]
        public void AfterTest()
        {
            // TODO unit test for the property 'After'
        }

    }

}
