/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.Net.Api;
using Acme.Net.Model;
using Acme.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.Net.Test.Model
{
    /// <summary>
    ///  Class for testing PaginateResponseEdgesNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginateResponseEdgesNodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginateResponseEdgesNode
        //private PaginateResponseEdgesNode instance;

        public PaginateResponseEdgesNodeTests()
        {
            // TODO uncomment below to create an instance of PaginateResponseEdgesNode
            //instance = new PaginateResponseEdgesNode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginateResponseEdgesNode
        /// </summary>
        [Fact]
        public void PaginateResponseEdgesNodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginateResponseEdgesNode
            //Assert.IsType<PaginateResponseEdgesNode>(instance);
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
