/* DO NOT TOUCH: This file was generated by Konfig */

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * A category for a pet
 */
export type Category = {
    id?: number;
    name?: string;
};

