#import <Foundation/Foundation.h>
#import "AObject.h"

/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "ACategory.h"
#import "ATag.h"
@protocol ACategory;
@class ACategory;
@protocol ATag;
@class ATag;



@protocol APet
@end

@interface APet : AObject


@property(nonatomic) NSArray<ATag>* tags;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) ACategory* category;

@property(nonatomic) NSString* name;

@property(nonatomic) NSArray<NSString*>* photoUrls;
/* pet status in the store [optional]
 */
@property(nonatomic) NSString* status;

@end
