//
// PaginateRequest.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaginateRequest: Codable, JSONEncodable, Hashable {

    public var first: Int?
    public var after: String?

    public init(first: Int? = nil, after: String? = nil) {
        self.first = first
        self.after = after
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case first
        case after
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(first, forKey: .first)
        try container.encodeIfPresent(after, forKey: .after)
    }
}

