//
// Pet.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A pet for sale in the pet store */
public struct Pet: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case available = "available"
        case pending = "pending"
        case sold = "sold"
    }
    public var tags: [Tag]?
    public var id: Int64?
    public var category: Category?
    public var name: String
    public var photoUrls: [String]
    /** pet status in the store */
    @available(*, deprecated, message: "This property is deprecated.")
    public var status: Status?

    public init(tags: [Tag]? = nil, id: Int64? = nil, category: Category? = nil, name: String, photoUrls: [String], status: Status? = nil) {
        self.tags = tags
        self.id = id
        self.category = category
        self.name = name
        self.photoUrls = photoUrls
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tags
        case id
        case category
        case name
        case photoUrls
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encode(name, forKey: .name)
        try container.encode(photoUrls, forKey: .photoUrls)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

