/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.acme.client.models


import com.squareup.moshi.Json

/**
 * Describes the result of uploading an image resource
 *
 * @param code 
 * @param type 
 * @param message 
 */


data class ModelApiResponse (

    @Json(name = "code")
    val code: kotlin.Int? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "message")
    val message: kotlin.String? = null

)

