/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.acme.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param hasNextPage 
 * @param hasPreviousPage 
 * @param startCursor 
 * @param endCursor 
 */


data class PaginateResponsePageInfo (

    @Json(name = "hasNextPage")
    val hasNextPage: kotlin.Boolean? = null,

    @Json(name = "hasPreviousPage")
    val hasPreviousPage: kotlin.Boolean? = null,

    @Json(name = "startCursor")
    val startCursor: kotlin.String? = null,

    @Json(name = "endCursor")
    val endCursor: kotlin.String? = null

)

