/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.acme.client.models

import com.acme.client.models.PaginateResponseEdges
import com.acme.client.models.PaginateResponsePageInfo

import com.squareup.moshi.Json

/**
 * 
 *
 * @param edges 
 * @param pageInfo 
 */


data class PaginateResponse (

    @Json(name = "edges")
    val edges: PaginateResponseEdges? = null,

    @Json(name = "pageInfo")
    val pageInfo: PaginateResponsePageInfo? = null

)

