/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.acme.client.models

import com.acme.client.models.PaginateResponseEdgesNode

import com.squareup.moshi.Json

/**
 * 
 *
 * @param node 
 */


data class PaginateResponseEdges (

    @Json(name = "node")
    val node: PaginateResponseEdgesNode? = null

)

