/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.acme.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param first 
 * @param after 
 */


data class PaginateRequest (

    @Json(name = "first")
    val first: kotlin.Int? = null,

    @Json(name = "after")
    val after: kotlin.String? = null

)

