name: "konfig-detect-breaking-change"
on:
  pull_request:
    branches:
      - main
jobs:
  konfig-lint-openapi-spec:
    runs-on: ubuntu-latest
    env:
      CLI_VERSION: 1.0.181
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.CLI_VERSION }}
      - name: Install Konfig CLI
        run: npm install -g konfig-cli@$CLI_VERSION
      - name: Detect breaking change
        run: konfig detect-breaking-change -m ${{github.base_ref}} -s api-fixed.yaml
