name: Test Publish

on: push

jobs:

  # test_branch_name:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Get branch name
  #       id: get_branch_name
  #       run: |
  #         echo "bump-./v4:" | 
  #         sed 's/[^a-zA-Z0-9]/-/g' | 
  #         sed 's/--*/-/g' |
  #         sed 's/^-//g' | 
  #         sed 's/-$//g' |
  #         cut -c1-255

  test_publish:
    runs-on: ubuntu-latest
    container:
      image: konfigdev/konfig:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install konfig
        run: npm install -g konfig-cli

      - name: Give docker git permission
        run: git config --global --add safe.directory /__w/acme-sdks/acme-sdks

      - name: Check git status
        run: git status

      - name: Test publish
        run: konfig publish --skipTests -g python,typescript
        env:
          TWINE_USERNAME: "konfig"
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
