name: Test Publish

on: push

jobs:

  test_publish:
    runs-on: ubuntu-latest
    container:
      image: konfigdev/konfig:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install konfig
        run: npm install -g konfig-cli

      - name: Test publish
        run: konfig publish --skipTests -g python,typescript
