name: Test Publish

on: push

jobs:

  # test_branch_name:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Get branch name
  #       id: get_branch_name
  #       run: |
  #         echo "bump-./v4:" | 
  #         sed 's/[^a-zA-Z0-9]/-/g' | 
  #         sed 's/--*/-/g' |
  #         sed 's/^-//g' | 
  #         sed 's/-$//g' |
  #         cut -c1-255

  test_publish:
    runs-on: ubuntu-latest
    container:
      image: konfigdev/publish:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install konfig
        run: npm install -g konfig-cli

      - name: Give docker git permission
        run: git config --global --add safe.directory /__w/acme-sdks/acme-sdks

      - name: Check git status
        run: git status

      - name: Create link between python and python3
        run: ln -s /usr/bin/python3 /usr/bin/python

      - name: Authenticate npm
        run: echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm install
        working-directory: ./typescript

      - name: Clean git directory
        run: git stash -u

      - name: Test publish
        run: konfig publish --skipTests -g typescript
        env:
          TWINE_USERNAME: "konfig"
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
